#include "DirectX12Renderer_RenderFrame_04_MainPass_00_Shared.inl"
#include "DirectX12Renderer_RenderFrame_04_MainPass_01_Deferred.inl"
#include "DirectX12Renderer_RenderFrame_04_MainPass_02_Forward.inl"